server:
  port: 3500
  application:
    name: to-do-app

spring:
  data:
    mongodb:
      uri: mongodb+srv://unver:12345@atlascluster.9qm6i8s.mongodb.net/?retryWrites=true&w=majority
      database: todo-app-db

springdoc:
  swagger-ui:
    path: /api-doc

vaadin:
  excludeUrls: /swagger-ui/**
